# Generated by Django 4.1.7 on 2023-03-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
